baseurl = "http://web.mit.edu/hajsong/www/"
title = "Department of Atmospheric Sciences, Yonsei University"
theme = "hugo-universal-theme"


# Site language. Available translations in the theme's `/i18n` directory.


# languageCode = "en-us"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "yatmos"
# Enable Google Analytics by entering your tracking code
#googleAnalytics = "UA-117501743-1"
googleAnalytics = ""
hasCJKLanguage = true

# Define the number of posts per page
paginate = 20
summarylength = 20

[menu]

# Main menu

#[[menu.main]]
#    name = "Home"
#    url  = "/"
#    weight = 1

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 1

[[menu.main]]
    name = "People"
    identifier = "peo"
    url  = "/people/"
    weight = 3

#[[menu.main]]
#    name = "Faculty"
#    parent = "peo"
#    url  = "/people/faculty"
#    weight = 2.1

#[[menu.main]]
#    name = "Researchers"
#    parent = "peo"
#    url  = "/people/researcher"
#    weight = 2.2

#[[menu.main]]
#    name = "Students"
#    parent = "peo"
#    url  = "/people/students"
#    weight = 2.3

[[menu.main]]
    name = "Research"
    url  = "/research/"
    weight = 2

[[menu.main]]
    name = "News"
    url  = "/blog/"
    weight = 5

[[menu.main]]
    name = "Education"
    identifier = "edu"
    url  = "/education/"
    weight = 4

#[[menu.main]]
#    name = "Undergraduate"
#    parent = "edu"
#    url  = "/academics/undergraduate"
#    weight = 3.1

#[[menu.main]]
#    name = "Graduate"
#    parent = "edu"
#    url  = "/academics/graduate"
#    weight = 3.2

#[[menu.main]]
#    name = "Contact"
#    url  = "/contact/"
#    weight = 6

[[menu.topbar]]
    weight = 2
    name = "Language"
    url = "http://atmos.yonsei.ac.kr"
    pre = "한글"

[[menu.topbar]]
    weight = 1
    name = "School"
    url = "http://www.yonsei.ac.kr/en_sc/"
    pre = "YONSEI"

[params]
    viewMorePostLink = "/blog/"
    author = "YAtmos"
    defaultKeywords = ["atmos"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyAHcuGKNdKTQD9FNB4y1GL1mWgdzP1B2Rw"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "yonsei"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "yonseiatmos@gmail.com"

    about_us = "<p>Department of Atmospheric Sciences <br> College of Science <br> Yonsei University</p>"
    copyright = "Copyright (c) 2018 - 2018, Department of Atmospheric Sciences, Yonsei University; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # logo = "img/apple-touch-icon.png"

    address = """<p><strong>Department of Atmospheric Sciences</strong>
        <br><strong>Yonsei University</strong>
        <br>50 Yonsei-ro
        <br>Shinchon-dong
        <br>Seodaemoon-gu
        <br>Seoul, South Korea
        <br>03722
      </p>
      """
    latitude = "37.564044"
    longitude = "126.934705"
    direction = "25 Yeonhui-dong, Seodaemun-gu, Seoul, South Korea"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = false
    search = true
    teams = true

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.movie]
    enable = true
    #moviefile = "http://thenewcode.com/assets/videos/polina.mp4"
    moviefile = "img/iss.mp4"
    snapfile = "img/iss_ini.jpg"
    sourcefile = "https://youtu.be/W0LHTWG-UmQ"
    title = "Atmospheric Sciences?"
    subtitle = "Atmospheric sciences can provide responsible solutions for the global environment, the most challenging issue in the 21st century, and harmonious coexsitence of nature and human beings."

[params.see_more]
    enable = true
    icon = "fa fa-paper-plane"
    title = "Apply"
    subtitle = "We are looking forward to your participation."
    link_url = "education"
    link_text = "Check out our education program"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Congratulations!"
    subtitle = "Congratulations for winning awards."

[params.recent_posts]
    enable = true
    title = "News and Events"
    subtitle = "See the News tab for further details."

[taxonomies]
    tag = "tags"
    category = "categories"
    team = "teams"
